import { Geist, Geist_Mono, Urbanist, PT_Serif } from "next/font/google";

import "../globals.css";
import Navigation from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const ptSerif = PT_Serif({
  variable: "--font-pt-serif",
  subsets: ["latin"],
  weight: ["700"],
});
const urbanist = Urbanist({
  // variable: "--font-urbanist",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${ptSerif.variable} ${urbanist.className} ${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <Navigation />

        <div className="pt-20  ">{children}</div>

        <Footer />
      </body>
    </html>
  );
}
